export const CREATE_EQUIPE_SUCCESS = 'CREATE_EQUIPE_SUCCESS';
export const CREATE_EQUIPE_FAIL = 'CREATE_EQUIPE_FAIL';

export const FETCH_EQUIPES_REQUEST = 'FETCH_EQUIPES_REQUEST';
export const FETCH_EQUIPES_SUCCESS = 'FETCH_EQUIPES_SUCCESS';
export const FETCH_EQUIPES_FAILURE = 'FETCH_EQUIPES_FAILURE';
export const DELETE_EQUIPE_SUCCESS = 'DELETE_EQUIPE_SUCCESS';
export const LOAD_EQUIPE = 'LOAD_EQUIPE';
export const FAIL_EQUIPE = 'FAIL_EQUIPE';
export const LEAVE_EQUIPE_SUCCESS = 'LEAVE_EQUIPE_SUCCESS';
export const UPDATE_EQUIPE_SUCCESS = 'UPDATE_EQUIPE_SUCCESS';
export const FETCH_EQUIPES='FETCH_EQUIPES'
export const FETCH_ALLEQUIPES_SUCCESS='FETCH_ALLEQUIPES_SUCCESS'
export const ADD_TO_TEAM="ADD_TO_TEAM"




