version: '3.8'

services:
  frontend:
    image: siwarenf/projectmanagemntapp-frontend:latest
    ports:
      - "3000:80"
    networks:
      - my-network

  backend:
    image: siwarenf/projectmanagemntapp:latest
    ports:
      - "8000:8000"
    networks:
      - my-network
    environment:
      - MONGO_URL=mongodb://mongo:27017/projectmanagement

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
